[workspace]
members = ["apps/desktop/src-tauri", "crates/desktop-capture", "crates/desktop-input"]
exclude = ["vender/rust-sdks"]
resolver = "2"

[patch.crates-io]
libwebrtc = { git = "https://github.com/99percentpeople/rust-sdks.git", rev = "6270fa6cf42f9f4c9247b6c67377a6627eeba348" }
webrtc-sys = { git = "https://github.com/99percentpeople/rust-sdks.git", rev = "6270fa6cf42f9f4c9247b6c67377a6627eeba348" }

[profile.release]
codegen-units = 1
lto = true
strip = true
