services:
  weblink:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Set your public websocket url here, example:
        - VITE_WEBSOCKET_URL=ws://192.168.8.100:8080/ws
        - WEBLINK_STUN_SERVERS=stun:stun.l.google.com,stun:stun1.l.google.com
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - ENABLE_SSL=${ENABLE_SSL:-false}
    volumes:
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - ws-server

  ws-server:
    build:
      context: ./servers/weblink-ws-server
    environment:
      - LOG_LEVEL=info
    ports:
      - "9000:9000"
