fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "runtime_capabilities",
            "capture_sources",
            "capture_display_layout",
            "capture_thumbnail",
            "capture_codecs",
            "capture_backends",
            "capture_encoders",
            "capture_start",
            "capture_status",
            "capture_stop",
            "capture_share_start",
            "capture_set_audio_enabled",
            "capture_update_video_settings",
            "capture_video_stats",
            "capture_pipeline_stats",
            "capture_preview_open",
            "capture_preview_frame",
            "capture_preview_close",
            "capture_offer",
            "capture_answer",
            "capture_add_ice_candidate",
            "capture_close_peer",
        ]),
    ))
    .expect("could not build desktop configuration");
}
