//! Opt-in real duplication checks. Desktop pixels remain in local GPU/readback
//! buffers; no image is saved, transmitted or included in test output.
use super::*;
use crate::surface::{readback::Readback, FrameSink, TextureFrame};
use std::time::{Duration, Instant};
use tokio::sync::Notify;
use windows::Win32::{
    Foundation::FILETIME,
    System::Threading::{GetCurrentThread, GetThreadTimes},
};

struct Sink {
    readback: Mutex<Readback>,
    first: mpsc::SyncSender<()>,
    sent: AtomicBool,
}
impl FrameSink for Sink {
    fn frame(&self, frame: TextureFrame<'_>) -> Result<()> {
        self.readback.lock().unwrap().copy(&frame)?;
        if !self.sent.swap(true, Ordering::AcqRel) {
            let _ = self.first.send(());
        }
        Ok(())
    }
}

#[test]
#[ignore = "Requires an unlocked Windows desktop; captures locally without saving images"]
fn native_dxgi_final_frame_survives_stop_and_readback_device_is_reusable() {
    let runtime = tokio::runtime::Runtime::new().unwrap();
    let monitor = windows_capture::monitor::Monitor::enumerate().unwrap()[0];
    for round in 0..3 {
        let (first, received) = mpsc::sync_channel(1);
        let sink = Arc::new(Sink {
            readback: Mutex::new(Readback::default()),
            first,
            sent: AtomicBool::new(false),
        });
        let frames = Arc::new(Mutex::new(Frames {
            sink: Some(sink.clone()),
            ..Default::default()
        }));
        let session = start(monitor.as_raw_hmonitor() as usize, frames.clone()).unwrap();
        received
            .recv_timeout(Duration::from_secs(5))
            .expect("DXGI delivered no frame");
        // Allow the producer to return to AcquireNextFrame. No new desktop
        // event is generated by the test to unblock either readback or stop.
        thread::sleep(Duration::from_millis(75));
        let stopped = Instant::now();
        session.stop().unwrap();
        let stop_time = stopped.elapsed();
        assert!(
            stop_time < Duration::from_millis(500),
            "DXGI did not stop promptly: {stop_time:?}"
        );
        assert!(frames.lock().unwrap().closed);
        let notify = Arc::new(Notify::new());
        let mut source = sink.readback.lock().unwrap();
        let size = source.size;
        let mut pending = source.submit_notifying(size, None, notify.clone()).unwrap();
        drop(source);
        runtime.block_on(async {
            tokio::time::timeout(Duration::from_secs(3), async {
                loop {
                    notify.notified().await;
                    if let Some(mapped) = pending.try_map().unwrap() {
                        assert_eq!(
                            mapped.bytes().len(),
                            mapped.stride() as usize * size.1 as usize
                        );
                        break;
                    }
                }
            })
            .await
            .expect("Final retained frame was lost after duplication stopped");
        });
        println!(
            "DXGI_STOP round={round} stopMs={:.3} finalReadback=ok",
            stop_time.as_secs_f64() * 1000.0
        );
    }
}

fn cpu_seconds() -> f64 {
    let (mut created, mut exited, mut kernel, mut user) = (
        FILETIME::default(),
        FILETIME::default(),
        FILETIME::default(),
        FILETIME::default(),
    );
    unsafe {
        GetThreadTimes(
            GetCurrentThread(),
            &mut created,
            &mut exited,
            &mut kernel,
            &mut user,
        )
    }
    .unwrap();
    let ticks =
        |time: FILETIME| (u64::from(time.dwHighDateTime) << 32) | u64::from(time.dwLowDateTime);
    (ticks(kernel) + ticks(user)) as f64 / 10_000_000.0
}

#[test]
#[ignore = "Opt-in real desktop acquire-wait comparison; no readback, encoding or display latency"]
fn native_dxgi_acquire_wait_cost() {
    let duplication = Duplication::open(None).unwrap();
    for polling in [true, false, false, true] {
        let (mut calls, mut frames, mut timeouts) = (0, 0, 0);
        let cpu = cpu_seconds();
        let started = Instant::now();
        while started.elapsed() < Duration::from_secs(3) {
            let mut info = DXGI_OUTDUPL_FRAME_INFO::default();
            let mut resource = None;
            let result = unsafe {
                duplication.output.AcquireNextFrame(
                    if polling { 0 } else { ACQUIRE_TIMEOUT_MS },
                    &mut info,
                    &mut resource,
                )
            };
            calls += 1;
            match result {
                Ok(()) => {
                    let _lease = FrameLease(&duplication.output);
                    frames += 1;
                }
                Err(error) if error.code() == DXGI_ERROR_WAIT_TIMEOUT => {
                    timeouts += 1;
                    if polling {
                        thread::sleep(Duration::from_millis(1));
                    }
                }
                Err(error) => panic!("Desktop capture was interrupted during measurement: {error}"),
            }
        }
        println!(
            "DXGI_ACQUIRE_COST {}",
            serde_json::json!({
                "polling": polling, "calls": calls, "frames": frames, "timeouts": timeouts,
                "wallSeconds": started.elapsed().as_secs_f64(), "cpuSeconds": cpu_seconds() - cpu,
            })
        );
    }
}
